services:
  edge:
    image: stmodanscs/edge
    container_name: edge
    entrypoint: /entrypoint.sh
    environment:
      USER: user1
      PASS: password1
      SSH:  yes
      #WEB: yes
    networks:
      localnet:
        ipv4_address: 192.168.0.3
      hacklab00_net:
      hacklab01_net:
      hacklab02_net:
      hacklab03_net:
      hacklab04_net:
      hacklab05_net:

networks:
  localnet:
    name: localnet
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: 192.168.0.0/24
  # see ../hacklabXX/compose.yaml
  hacklab00_net:
    external: true
  hacklab01_net:
    external: true
  hacklab02_net:
    external: true
  hacklab03_net:
    external: true
  hacklab04_net:
    external: true
  hacklab05_net:
    external: true
