services:
  edge:
    image: stmodanscs/edge
    container_name: edge
    entrypoint: /entrypoint.sh
    environment:
      USER: user1
      PASS: password1
      SSH:  yes
      #WEB: yes
    networks:
      localnet:
        # local ip address (change this)
        ipv4_address: 192.168.0.2
      # hacklabs
      hacklab00_net:
      hacklab01_net:
      hacklab02_net:

networks:
  localnet:
    name: localnet
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        # local ip subnet (change this)
        - subnet: 192.168.0.0/16
  # hacklabs
  hacklab00_net:
    external: true
  hacklab01_net:
    external: true
  hacklab02_net:
    external: true
