services:
  hacklabXXXX_kali:
    image: stmodanscs/kali-2023.1
    container_name: hacklabXXXX_kali
    entrypoint: /entrypoint.sh
    environment:
      PASS: myPass
      ROOT: yes
      SSH:  yes
    networks:
      hacklabXXXX_localnet:
        ipv4_address: 172.0.XXXX.11
#      hacklabXXXX_hacknet:
#        ipv4_address: 172.1.XXXX.11

  hacklabXXXX_metasploitable2:
    image: stmodanscs/metasploitable2
    container_name: hacklabXXXX_metasploitable2
    entrypoint: /entrypoint.sh
    environment:
      PASS: myPass
      ROOT: yes
      SSH:  yes
      #CUPS: yes
      #FTP:  yes
      #HTTP: yes
      #IRC:  yes
      SMB:  yes
      #SQL:  yes
    networks:
      hacklabXXXX_localnet:
        ipv4_address: 172.0.XXXX.12

  hacklabXXXX_metasploitable3:
    image: stmodanscs/metasploitable3-ub1404
    container_name: hacklabXXXX_metasploitable3
    entrypoint: /entrypoint.sh
    environment:
      PASS: myPass
      ROOT: yes
      SSH:  yes
      CUPS: yes
      FTP:  yes
      HTTP: yes
      IRC:  yes
      SMB:  yes
      SQL:  yes
    networks:
      hacklabXXXX_localnet:
        ipv4_address: 172.0.XXXX.13

networks:
  hacklabXXXX_localnet:
    name: hacklabXXXX_localnet
    internal: true
    ipam:
      config:
        - subnet: 172.0.XXXX.0/24
#  hacklabXXXX_hacknet:
#    name: hacklabXXXX_hacknet
#    driver: macvlan
#    driver_opts:
#      parent: ens19
#    ipam:
#      config:
#        - subnet: 172.1.0.0/16