services:
  hacklabXXXX_kali:
    image: stmodanscs/kali-2023.1
    container_name: hacklabXXXX_kali
    entrypoint: /entrypoint.sh
    environment:
      PASS: myPass
      ROOT: yes
      SSH:  yes
    networks:
      hacklabXXXX_net:
        ipv4_address: 172.0.XXXX.11
      hacknet:
        ipv4_address: 172.1.XXXX.11

  hacklabXXXX_metasploitable2:
    image: stmodanscs/metasploitable2
    container_name: hacklabXXXX_metasploitable2
    entrypoint: /entrypoint.sh
    environment:
      PASS: myPass
      ROOT: yes
      SSH:  yes
      #CUPS: yes
      #FTP:  yes
      #HTTP: yes
      #IRC:  yes
      SMB:  yes
      #SQL:  yes
    networks:
      hacklabXXXX_net:
        ipv4_address: 172.0.XXXX.12

  hacklabXXXX_metasploitable3:
    image: stmodanscs/metasploitable3-ub1404
    container_name: hacklabXXXX_metasploitable3
    entrypoint: /entrypoint.sh
    environment:
      PASS: myPass
      ROOT: yes
      SSH:  yes
      CUPS: yes
      FTP:  yes
      HTTP: yes
      IRC:  yes
      SMB:  yes
      SQL:  yes
    networks:
      hacklabXXXX_net:
        ipv4_address: 172.0.XXXX.13


networks:
  hacklabXXXX_net:
    name: hacklabXXXX_net
    driver_opts:
      com.docker.network.bridge.inhibit_ipv4: "true"
    internal: true
    ipam:
      config:
        - subnet: 172.0.XXXX.0/24
  # see ../networks/compose.yaml
  hacknet:
    external: true
