networks:
  localnet:
    name: localnet
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: 192.168.0.0/24
  hacknet:
    name: hacknet
    driver: macvlan
    driver_opts:
      macvlan_mode: private
      parent: ens19
    ipam:
      config:
        - subnet: 172.1.0.0/16
